version: '3.8'

services:
  peer1:
    build: .
    ports:
      - "7777:7777"
    environment:
      - PORT=7777
    stdin_open: true  # Enable STDIN
    tty: true         # Allocate pseudo-TTY
    networks:
      - p2p-net

  peer2:
    build: .
    ports:
      - "7778:7778"
    environment:
      - PORT=7778
    stdin_open: true
    tty: true
    networks:
      - p2p-net

networks:
  p2p-net:
    driver: bridge