version: '3.8'

services:
  peer1:
    build: .
    container_name: peer1
    tty: true
    stdin_open: true
    ports:
      - "7777:7777"
    environment:
      - PEER_NAME=Peer-1
    command: sh -c "echo $$PEER_NAME > /app/config/username && java -jar connect4-p2p.jar"
    networks:
      p2p-network:
        ipv4_address: 172.20.0.10

  peer2:
    build: .
    container_name: peer2
    tty: true
    stdin_open: true
    environment:
      - PEER_NAME=Peer-2
    command: sh -c "echo $$PEER_NAME > /app/config/username && java -jar connect4-p2p.jar"
    networks:
      p2p-network:
        ipv4_address: 172.20.0.11

  peer3:
    build: .
    container_name: peer3
    tty: true
    stdin_open: true
    environment:
      - PEER_NAME=Peer-3
    command: sh -c "echo $$PEER_NAME > /app/config/username && java -jar connect4-p2p.jar"
    networks:
      p2p-network:
        ipv4_address: 172.20.0.12

  peer4:
    build: .
    container_name: peer4
    tty: true
    stdin_open: true
    environment:
      - PEER_NAME=Peer-4
    command: sh -c "echo $$PEER_NAME > /app/config/username && java -jar connect4-p2p.jar"
    networks:
      p2p-network:
        ipv4_address: 172.20.0.13

networks:
  p2p-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24