networks:
  p2p-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

services:
  bootstrap:
    build: .
    networks:
      p2p-network:
        ipv4_address: 192.168.0.26
    environment:
      MY_IP: "192.168.0.26"
      BOOTSTRAP_IP: "192.168.0.26"
      USERNAME: "bootstrap"
    stdin_open: true
    tty: true

  peer2:
    build: .
    networks:
      p2p-network:
        ipv4_address: 192.168.0.27
    environment:
      MY_IP: "192.168.0.27"
      BOOTSTRAP_IP: "192.168.0.26"
      USERNAME: "peer2"
    depends_on:
      - bootstrap
    stdin_open: true
    tty: true

  peer3:
    build: .
    networks:
      p2p-network:
        ipv4_address: 192.168.0.28
    environment:
      MY_IP: "192.168.0.28"
      BOOTSTRAP_IP: "192.168.0.26"
      USERNAME: "peer3"
    depends_on:
      - bootstrap
    stdin_open: true
    tty: true

  peer4:
    build: .
    networks:
      p2p-network:
        ipv4_address: 192.168.0.29
    environment:
      MY_IP: "192.168.0.29"
      BOOTSTRAP_IP: "192.168.0.26"
      USERNAME: "peer4"
    depends_on:
      - bootstrap
    stdin_open: true
    tty: true